apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-5jhr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0006-tenant/tkrw-pr712-0075-0006-app/devfile-sample-5jhr@sha256:bc25514e0f84697fc54ae924ed514e51b2b30c27bfb6b03da3f5c1754f76aab5
        name: my-nodejs
        resources: {}
status: {}
